file=open('myinfo.html','w')
file.write('<!doctype.html> \n')
file.write('<html> \n')
file.write('<br/> \n')
file.write('<head><title>myinformation</title></head> \n')
file.write('<br/> \n')
file.write('\t <body> \n')
file.write('\t\t <br/> \n')
file.write('\t\t <h1 align=center> \n')
name=input('enter your name: \n')
file.write('\t\t'+name)
file.write('\t\t</h1> \n')
file.write('<hr width="100%">')
file.write('\t\t <br/> \n')
major=input('MAJOR: \n')
interest=input('INTEREST: \n')
experience=input('EXPERIENCE: \n')
research=input('research: \n')
file.write('\t\t <p> \n')
file.write('\t\t <br/> \n')
file.write('\t\t MAJOR:'+major)
file.write('\t\t<br/> \n')
file.write('\t\t INTERSET:'+interest)
file.write('<br/> \n')
file.write('\t\t EXPERIENCE:'+experience)
file.write('<br/> \n')
file.write('\t\t RESEARCH:'+research)
file.write('<br/> \n')
file.write('\t\t </p> \n')

file.write('\t </body> \n')
file.write('<br/> \n')
file.write('</html> \n')
file.close()
